version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - "8084:8084" # Expose the Go app on port 8080
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASS=root
      - DB_NAME=proxy_experiment
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: proxy_experiment
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20


networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
